import { test, expect } from 'vitest'
import { langFor, isHighlightable } from '../fileLang'

test('langFor: 配置类', () => {
  expect(langFor('a.yaml')).toBe('yaml')
  expect(langFor('a.YML')).toBe('yaml')
  expect(langFor('config.json')).toBe('json')
  expect(langFor('pyproject.toml')).toBe('toml')
  expect(langFor('app.ini')).toBe('ini')
  expect(langFor('a.cfg')).toBe('ini')
  expect(langFor('logger.properties')).toBe('properties')
})
test('langFor: 脚本/语言', () => {
  expect(langFor('run.sh')).toBe('bash')
  expect(langFor('main.py')).toBe('python')
  expect(langFor('i.js')).toBe('javascript')
  expect(langFor('m.mjs')).toBe('javascript')
  expect(langFor('a.ts')).toBe('typescript')
  expect(langFor('main.go')).toBe('go')
  expect(langFor('lib.rs')).toBe('rust')
  expect(langFor('App.java')).toBe('java')
  expect(langFor('a.c')).toBe('c')
  expect(langFor('a.h')).toBe('c')
  expect(langFor('a.cpp')).toBe('cpp')
  expect(langFor('a.cs')).toBe('csharp')
  expect(langFor('q.sql')).toBe('sql')
  expect(langFor('web.rb')).toBe('ruby')
  expect(langFor('svc.php')).toBe('php')
})
test('langFor: 标记/web', () => {
  expect(langFor('page.html')).toBe('markup')
  expect(langFor('data.xml')).toBe('markup')
  expect(langFor('s.svg')).toBe('markup')
  expect(langFor('style.css')).toBe('css')
  expect(langFor('README.md')).toBe('markdown')
  expect(langFor('q.graphql')).toBe('graphql')
  expect(langFor('p.diff')).toBe('diff')
})
test('langFor: 无扩展名特判 + 大小写不敏感', () => {
  expect(langFor('Dockerfile')).toBe('docker')
  expect(langFor('DOCKERFILE')).toBe('docker')
  expect(langFor('Makefile')).toBe('makefile')
})
test('langFor: 未命中 → none', () => {
  expect(langFor('notes')).toBe('none')
  expect(langFor('weird.xyz')).toBe('none')
  expect(langFor('')).toBe('none')
  expect(langFor(undefined)).toBe('none')
  expect(langFor('path/noext/file')).toBe('none')
})
test('isHighlightable', () => {
  expect(isHighlightable('a.js')).toBe(true)
  expect(isHighlightable('notes')).toBe(false)
})
